destination_server: https://kubernetes.default.svc

targetRevision: main

repoURL: https://github.com/Karl-br/ts0624.git

project: default

apps:
    - name: api-auth
      namespace: 001
      helmfile: api-auth.yaml
